[package]
name = "bicdb-pgwire"
version = "1.0.438-beta"
edition.workspace = true
license-file.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
axum-server.workspace = true
argon2.workspace = true
base64.workspace = true
bicdb-core = { path = "../bicdb-core", version = "1.0.438-beta" }
bicdb-sql = { path = "../bicdb-sql", version = "1.0.438-beta" }
ctrlc.workspace = true
hex.workspace = true
hmac.workspace = true
libc.workspace = true
parking_lot.workspace = true
pbkdf2.workspace = true
rustc-hash.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlparser.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

x509-parser.workspace = true

[dev-dependencies]
openssl = "0.10"
postgres-openssl = "0.5.3"
serde_json.workspace = true
sqlx = { version = "=0.8.6", default-features = false, features = ["runtime-tokio", "postgres"] }
tempfile.workspace = true
tokio.workspace = true
tokio-postgres = "0.7.18"
uuid.workspace = true
