[package]
name = "bicdb-provider-redis"
version = "1.0.438-beta"
edition.workspace = true
license = "Apache-2.0"
rust-version.workspace = true

[dependencies]
base64.workspace = true
bicdb-app-runtime = { path = "../bicdb-app-runtime", version = "1.0.438-beta" }
r2d2.workspace = true
redis.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
