CREATE TYPE dump_mood AS ENUM ('calm', 'busy', 'done');
CREATE DOMAIN dump_positive AS numeric(12,2) CHECK (VALUE >= 0);
CREATE TYPE dump_pair AS (code integer, label text);
CREATE TYPE dump_intrange AS RANGE (subtype = integer);
CREATE TYPE dump_code;
CREATE FUNCTION dump_code_in(cstring) RETURNS dump_code
    AS 'textin' LANGUAGE internal IMMUTABLE STRICT;
CREATE FUNCTION dump_code_out(dump_code) RETURNS cstring
    AS 'textout' LANGUAGE internal IMMUTABLE STRICT;
CREATE FUNCTION dump_code_recv(internal) RETURNS dump_code
    AS 'textrecv' LANGUAGE internal IMMUTABLE STRICT;
CREATE FUNCTION dump_code_send(dump_code) RETURNS bytea
    AS 'textsend' LANGUAGE internal IMMUTABLE STRICT;
CREATE TYPE dump_code (
    INPUT = dump_code_in,
    OUTPUT = dump_code_out,
    RECEIVE = dump_code_recv,
    SEND = dump_code_send,
    INTERNALLENGTH = variable,
    ALIGNMENT = int4,
    STORAGE = extended,
    CATEGORY = 'S',
    DELIMITER = ';'
);

CREATE TABLE dump_type_families (
    id uuid PRIMARY KEY,
    bool_value boolean,
    small_value smallint,
    int_value integer,
    big_value bigint,
    real_value real,
    double_value double precision,
    exact_value numeric(19,4),
    money_value money,
    char_value char(4),
    varchar_value varchar(32),
    text_value text,
    bytes_value bytea,
    bit_value bit(4),
    varbit_value bit varying(8),
    date_value date,
    time_value time(6),
    timetz_value time(6) with time zone,
    timestamp_value timestamp(6),
    timestamptz_value timestamp(6) with time zone,
    interval_value interval,
    json_value json,
    jsonb_value jsonb,
    jsonpath_value jsonpath,
    xml_value xml,
    inet_value inet,
    cidr_value cidr,
    mac_value macaddr,
    mac8_value macaddr8,
    point_value point,
    line_value line,
    lseg_value lseg,
    box_value box,
    path_value path,
    polygon_value polygon,
    circle_value circle,
    document_vector tsvector,
    document_query tsquery,
    int4_span int4range,
    int8_span int8range,
    numeric_span numrange,
    timestamp_span tsrange,
    timestamptz_span tstzrange,
    date_span daterange,
    int4_spans int4multirange,
    int8_spans int8multirange,
    numeric_spans nummultirange,
    timestamp_spans tsmultirange,
    timestamptz_spans tstzmultirange,
    date_spans datemultirange,
    mood_value dump_mood,
    positive_value dump_positive,
    pair_value dump_pair,
    custom_span dump_intrange,
    code_value dump_code,
    code_values dump_code[],
    oid_value oid,
    lsn_value pg_lsn,
    snapshot_value pg_snapshot,
    xid_value xid,
    xid8_value xid8,
    cid_value cid,
    tid_value tid,
    int_values integer[],
    exact_values numeric(9,2)[],
    uuid_values uuid[],
    mood_values dump_mood[],
    range_values int4range[],
    pair_values dump_pair[]
);

INSERT INTO dump_type_families VALUES (
    '018f3c7a-89ab-7def-8123-456789abcdef',
    true, -32768, 2147483647, 9007199254740993,
    1.25, -2.5, 123456789012345.5000, 12.34,
    'AB', 'portable', 'BicDB and PostgreSQL', '\x00ff', B'1010', B'101011',
    DATE '2026-07-19', TIME '12:34:56.123456', TIMETZ '12:34:56.123456+02',
    TIMESTAMP '2026-07-19 12:34:56.123456',
    TIMESTAMPTZ '2026-07-19 12:34:56.123456+00',
    INTERVAL '1 year 2 mons 3 days 04:05:06.123456',
    '{"exact":"9007199254740993.01"}',
    '{"items":[1,2,3],"ok":true}',
    '$.items[*] ? (@ > 1)',
    '<root exact="true">portable</root>',
    '2001:db8::1/64', '2001:db8::/64', '08:00:2b:01:02:03',
    '08:00:2b:ff:fe:01:02:03',
    '(1.5,-2.25)', '{1,2,3}', '[(0,0),(2,2)]', '(2,2),(0,0)',
    '[(0,0),(1,1),(2,0)]', '((0,0),(2,0),(1,2))', '<(1,2),3.5>',
    to_tsvector('simple', 'alpha beta beta'), to_tsquery('simple', 'alpha & beta'),
    '[1,10)', '[9007199254740993,9007199254741000)', '[0.10,9.99)',
    '[2026-07-19 00:00:00,2026-07-20 00:00:00)',
    '[2026-07-19 00:00:00+00,2026-07-20 00:00:00+00)',
    '[2026-07-19,2026-07-20)',
    '{[1,3),[5,8)}', '{[9007199254740993,9007199254741000)}',
    '{[0.10,1.00),[2.00,9.99)}',
    '{[2026-07-19 00:00:00,2026-07-20 00:00:00)}',
    '{[2026-07-19 00:00:00+00,2026-07-20 00:00:00+00)}',
    '{[2026-07-19,2026-07-20)}',
    'busy', 42.50, ROW(7, 'seven')::dump_pair, '[4,9)'::dump_intrange,
    'alpha'::dump_code, '{alpha;beta}'::dump_code[],
    42, '0/16B6C50', '10:20:12,15', '42', '43', '1', '(1,2)',
    ARRAY[1,2,3], ARRAY[0.10,9000.25]::numeric(9,2)[],
    ARRAY['018f3c7a-89ab-7def-8123-456789abcdef'::uuid],
    ARRAY['calm'::dump_mood,'done'::dump_mood],
    ARRAY['[1,3)'::int4range,'empty'::int4range],
    ARRAY[ROW(1,'one')::dump_pair,ROW(2,'two')::dump_pair]
);

CREATE TABLE dump_identity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id uuid NOT NULL REFERENCES dump_type_families(id),
    label text NOT NULL
);

INSERT INTO dump_identity (family_id, label)
VALUES ('018f3c7a-89ab-7def-8123-456789abcdef', 'identity survives');

CREATE VIEW dump_type_view AS
SELECT id, exact_value, mood_value FROM dump_type_families;

CREATE TABLE dump_row_source (
    code integer,
    label text
);

CREATE TABLE dump_row_holder (
    id integer PRIMARY KEY,
    item dump_row_source,
    items dump_row_source[]
);

INSERT INTO dump_row_holder VALUES (
    1,
    ROW(7, 'seven')::dump_row_source,
    ARRAY[
        ROW(8, 'eight')::dump_row_source,
        ROW(9, 'nine')::dump_row_source
    ]
);
