//! Regression: pg_dump emits identity columns as a standalone
//! `ALTER TABLE ... ALTER COLUMN ... ADD GENERATED ... AS IDENTITY
//! (SEQUENCE NAME ... START WITH ... )`. sqlparser rejects the
//! parenthesized sequence options ("Expected: ), found: SEQUENCE"), which
//! was the first hard failure restoring a production dump on 1.0.176-beta.

use bicdb_core::{BicDb, DbConfig, StorageMode};
use bicdb_sql::{SqlSession, SqlValue};

fn session_db() -> (tempfile::TempDir, BicDb) {
    let dir = tempfile::tempdir().unwrap();
    let db = BicDb::open_with_config(
        dir.path(),
        DbConfig::default()
            .with_fsync(false)
            .with_storage_mode(StorageMode::ServerPaged),
    )
    .unwrap();
    (dir, db)
}

#[test]
fn add_generated_as_identity_with_sequence_name_options() {
    let (_dir, mut db) = session_db();
    let mut sql = SqlSession::new(&mut db);

    // The pg_dump restore order: table, then the backing sequence, then the
    // identity attach referencing it by SEQUENCE NAME.
    sql.execute("CREATE TABLE public.carrier_events (sequence BIGINT NOT NULL, body TEXT)")
        .unwrap();
    sql.execute("CREATE SEQUENCE public.carrier_events_sequence_seq")
        .unwrap();
    sql.execute(
        "ALTER TABLE public.carrier_events ALTER COLUMN sequence \
         ADD GENERATED BY DEFAULT AS IDENTITY ( \
           SEQUENCE NAME public.carrier_events_sequence_seq \
           START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1 )",
    )
    .expect("pg_dump identity attach must parse and apply");

    // The column is now an identity column: inserts that omit it generate a
    // value, and it can't be set NULL.
    sql.execute("INSERT INTO public.carrier_events (body) VALUES ('a')")
        .unwrap();
    sql.execute("INSERT INTO public.carrier_events (body) VALUES ('b')")
        .unwrap();
    let rows = sql
        .execute("SELECT sequence FROM public.carrier_events ORDER BY sequence")
        .unwrap();
    assert_eq!(rows.rows.len(), 2);
    let ids: Vec<i64> = rows
        .rows
        .iter()
        .map(|row| match row[0] {
            SqlValue::Int(v) => v,
            ref other => panic!("expected int identity, got {other:?}"),
        })
        .collect();
    assert!(
        ids[0] >= 1 && ids[1] > ids[0],
        "identity values must ascend: {ids:?}"
    );

    // ALWAYS variant + the ONLY / no-COLUMN-keyword spellings pg_dump also
    // emits parse too.
    sql.execute("CREATE TABLE public.evt2 (id INTEGER NOT NULL)")
        .unwrap();
    sql.execute(
        "ALTER TABLE ONLY public.evt2 ALTER id \
         ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME public.evt2_id_seq)",
    )
    .expect("ALWAYS + ONLY + no COLUMN keyword must parse");
    sql.execute("INSERT INTO public.evt2 DEFAULT VALUES")
        .unwrap();
    let rows = sql.execute("SELECT count(*) FROM public.evt2").unwrap();
    assert_eq!(rows.rows[0][0], SqlValue::Int(1));

    // Non-integer identity is still rejected.
    sql.execute("CREATE TABLE public.bad (name TEXT NOT NULL)")
        .unwrap();
    assert!(sql
        .execute(
            "ALTER TABLE public.bad ALTER COLUMN name \
             ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.bad_name_seq)"
        )
        .is_err());
}
