[package]
name = "bicdb-provider-embeddings"
version = "1.0.438-beta"
edition.workspace = true
license = "Apache-2.0"
rust-version.workspace = true

[dependencies]
bicdb-app-runtime = { path = "../bicdb-app-runtime", version = "1.0.438-beta" }
bicdb-core = { path = "../bicdb-core", version = "1.0.438-beta" }
